spring:
  application:
    name: cart-service

  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configuration-server

  config:
    import: 'optional:configserver:'


  datasource:
    url: jdbc:h2:mem:car_db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: cart-service
    description: Service for managing carts-from github
    version: 1.0.0

eureka:
  instance:
    statusPageUrlPath: 'http://localhost:${server.port}/actuator/info'
    healthCheckUrlPath: 'http://localhost:${server.port}/actuator/health'
    hostname: localhost
