server:
  port: 8085

spring:
  application:
    name: ms-course
  #Use Config Server
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      discovery:
        enabled: true
        service-id: ms-config-server

  #Use DB
  datasource:
    url: jdbc:h2:mem:dbcourse
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    app:
      name: ${spring.application.name}
      description: Course Service
      version: 1.0.0

#Actuator Redirect URLs for Eureka
eureka:
  instance:
    statusPageUrlPath: http://localhost:${server.port}/actuator/info
    healthCheckUrlPath: http://localhost:${server.port}/actuator/health