spring:
  application:
    name: ms-student
  #Use Config Server
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      discovery:
        enabled: true
        service-id: ms-config-server

server:
  port: 8084

custom:
  message: Loaded from Config Server

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    app:
      name: ${spring.application.name}
      description: Student Service
      version: 1.0.0

#Actuator Redirect URLs for Eureka
eureka:
  instance:
    statusPageUrlPath: http://localhost:${server.port}/actuator/info
    healthCheckUrlPath: http://localhost:${server.port}/actuator/health
#  hostname: localhost
